### PR TITLE
Bug: Clear side effects related to DOM event listeners

### LINKED ISSUE #104: Unregister event listeners on unmount
When unmounting this component, some events are still fired.

### Solution

Clean side effects related to DOM event listeners:
- Create instance methods so they remain unchanged for the `removeEventListener` call
- Add `componentWillUnmount` with all the `removeEventListener` calls

### PR DESCRIPTION
**Pull request by emibcn**
- Create instance methods so they remain unchanged for the `removeEventListener` call
- Add `componentWillUnmount` with all the `removeEventListener` calls

### CODE REVIEW

**Comment by emibcn** [comment]
Fixes #104

**Comment by emibcn** [comment]
Duplicate of https://github.com/justinmc/react-audio-player/issues/57

**Comment by justinmc** [comment]
I just made these optional so you've got conflicts now.  Would you be able to resolve them?

**Comment by emibcn** [comment]
> I just made these optional so you've got conflicts now. Would you be able to resolve them?

Sure! It will be done during today. Thanks for your time!

**Comment by emibcn** [comment]
Done! You can merge now without conflicts ;)

**Comment by emibcn** [comment]
Fixed the types of the arguments of the event listeners by changing `e: any` to `e: Event`.

**Comment by emibcn** [comment]
@justinmc Are you having any trouble with this PR? I can adapt it to whatever needs you have.

**Review by justinmc — APPROVED** [review]
LGTM, thanks for the quick response on this and sorry I was so slow!  I'll merge this and release a new version.

**Pull request merged**
