### PR TITLE
Volume prop

### PR DESCRIPTION
**Pull request by ajay-gandhi**
Add the `volume` prop to the component. Passed in volume must be between 0.0 (silent) and 1.0 (loudest); I can add a PropTypes validation for that if you'd like.

### CODE REVIEW

**Comment by justinmc** [comment]
@ajay-gandhi Awesome, thanks for adding this!  Not sure how I missed such an obvious prop...

I'll go ahead and merge this as-is, but if you're inclined to open another PR with the more specific prop type, I think that would be a great addition and I'd be happy to merge that PR as well.

Let me know and I'll release a new version with this change.  Thanks again!

**Comment by ajay-gandhi** [comment]
I actually think the additional validation might be unnecessary, it should be handled by the user and (worst-case) handled by the browser - not hard to add though, so I can definitely add it if you think it's worth :)

**Comment by womcauliff** [comment]
Hello,

**Passing an initial value for the `volume` prop on the `ReactAudioPlayer` Component is not working for me.**

I believe this is due to the fact that the `volume` attribute is **not implemented** by browsers for the HTML5 `<audio>` element:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#Browser_compatibility

Instead, every method I have found online to update the volume of an `audio` element involves using Javascript to retrieve the element, and update its `volume` **property**, not its **attribute.**
- https://stackoverflow.com/questions/33747398/html-audio-tag-volume
- https://www.w3schools.com/jsref/prop_audio_volume.asp

**Comment by ajay-gandhi** [comment]
@womcauliff I believe @justinmc hasn't updated the package in the NPM registry, so that might be why it's not working for you?

In case you're actually right, maybe we can add something like this:

```js
componentWillReceiveProps(nextProps) {
  if (nextProps.volume !== this.props.volume) {
    this.audioEl.volume = nextProps.volume;
  }
}
// Add something similar in the constructor or when setting the ref
```

This is what I'm currently using to update the volume for this component.

**Comment by justinmc** [comment]
@womcauliff I just published `v0.8.0`, please try that and let me know if the volume prop works.  @ajay-gandhi should be right about it not working due to not being published.  I'm happy to dig into this if something still seems wrong though.

**Comment by ajay-gandhi** [comment]
@justinmc Looks like @womcauliff might be right. I just upgraded `react-audio-player` and although the `volume` attribute gets updated on the `<audio />` element, the volume doesn't actually change.

I verified by querying the element through JS and printing the `volume` property.

**Comment by justinmc** [comment]
@ajay-gandhi I just released https://github.com/justinmc/react-audio-player/releases/tag/v0.9.0, and this time it should work!  It seems that React doesn't support the `volume` prop, so instead I manually handle setting it on the DOM element to the value that's passed in as props ([here in the code](https://github.com/justinmc/react-audio-player/blob/master/src/index.jsx#L84)).

To the end user this should work just like a simple property.  Let me know if it doesn't work for you.

**Comment by ajay-gandhi** [comment]
Hmm, still doesn't seem to be working, although the code you linked is exactly what I was doing as well - are you sure you published the minified code properly? I "unminified" it and couldn't find your changes.

**Comment by ajay-gandhi** [comment]
Never mind, must have been a mistake on my end. Looks good, thanks!

**Pull request merged**
