### PR TITLE
#61 move react-hot-loader to dependencies

### LINKED ISSUE #61: cannot find module react-hot-loader in version 0.11.1

### PR DESCRIPTION
**Pull request by mahboubii**
fixes #61

### CODE REVIEW

**Comment by JohnHeitmann** [comment]
`react-hot-loader` shouldn't be a full dependency. Based on some local testing, I think if @justinmc rebuilds with an updated dependency tree then babel (or whatever was doing it) will no longer add the react-hot-loader require into bundle.js; no source changes are required.

Alternately, removing `react-hot-loader` entirely could be appropriate. I'm not sure why it's here in the first place.

**Comment by OnkelTem** [comment]
Since when adding a dev module to prod deps is reckoned a fix? Sorry.

**Comment by mahboubii** [comment]
@OnkelTem you're right i didn't dig into the issue and source code to actually fix the problem, this is just to fix the build error.

**Comment by AshotN** [comment]
Is there plans to remove it fully? There hasn't been a release to NPM for a while and I just ran into this issue.

**Pull request closed without merging**
