### PR TITLE
Add ability to declare if you want to display controls or not

### PR DESCRIPTION
**Pull request by jblok**
Still defaults to true

### CODE REVIEW

**Comment by justinmc** [comment]
Thanks for the pull request!  I just noticed the other day that I had forgotten to make `controls` accessible via props.  Merging.

**Comment by justinmc** [comment]
I'll try to remember to release a new version that includes this change tonight.

**Comment by jblok** [comment]
Thanks for accepting my first ever open source PR :D

**Comment by justinmc** [comment]
🎉  Woo!  I'm honored.

**Comment by justinmc** [comment]
Released in v0.2.8

**Pull request merged**
